### ISSUE TITLE
Improve Ui Colors

### ISSUE THREAD

**Issue by MDOBreno** [AlvaroLopezCarrillo/TDT-Online-Spain#1]
Great repo!!
Just need to improve Ui colors(for text and background) from tableview, for both themes(dark and light).
Hint: Black background suits better for TV(For exemple: Netflix, Youtube,..), people usually turns the lights off while watching a movie(or something), and a big white screen blinds people.

**Comment by AlvaroLopezCarrillo** [comment]
Thanks for the feedback! I have changed the UI Colors now. It is better.
